CREATE TABLE IF NOT EXISTS users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name_user VARCHAR(255) NOT NULL,
    email    VARCHAR(512) NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT uq_user_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    description  VARCHAR(1000) NOT NULL,
    requester_id BIGINT        NOT NULL,
    created      TIMESTAMP,
    CONSTRAINT pk_request PRIMARY KEY (id),
    CONSTRAINT fk_requests_users FOREIGN KEY (requester_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name_item    VARCHAR(255)  NOT NULL,
    description  VARCHAR(1000) NOT NULL,
    is_available BOOLEAN       NOT NULL,
    owner_id     BIGINT,
    request_id   BIGINT,
    CONSTRAINT pk_item PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    start_date TIMESTAMP,
    end_date   TIMESTAMP,
    item_id    BIGINT NOT NULL,
    booker_id  BIGINT NOT NULL,
    status     VARCHAR(30),
    CONSTRAINT pk_booking PRIMARY KEY (id),
    CONSTRAINT fk_bookings_user FOREIGN KEY (booker_id) REFERENCES users (id),
    CONSTRAINT fk_bookings_item FOREIGN KEY (item_id) REFERENCES items (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text      varchar(1000)                           NOT NULL,
    item_id   BIGINT                                  NOT NULL,
    author_id BIGINT                                  NOT NULL,
    created   TIMESTAMP                               NOT NULL,
    CONSTRAINT fk_comments_items FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_comments_users FOREIGN KEY (author_id) REFERENCES users (id)
);